### ISSUE TITLE
New to Ember.Net - advice needed

### ISSUE THREAD

**Issue by AstecSteveB** [Lawo/ember-plus-sharp#18]
I've gone through the console application tutorial and can parse the tree loaded into TinyEmber+. I'm struggling to get data changes once running - creating a handler for PropertyChanged of a Parameter is not getting called. I can get a data update by using the same method as described in the static approach to reacting to changes. However, my driver will need to receive all parameter changes for a dynamic environment. I am wondering if I am missing a trick to get my consumer updated? I am running the Ember+ Viewer and can see update messages received as I change data in TinyEmber+ - this is what I need in my application :-)

**Comment by andreashuber-lawo** [comment]
> I've gone through the console application tutorial and can parse the tree loaded into TinyEmber+. I'm struggling to get data changes once running - creating a handler for PropertyChanged of a Parameter is not getting called.

Strange, you should be able to get exactly the same notifications through the dynamic Interface as you do through the static interface (it's the same implementation after all).

> However, my driver will need to receive all parameter changes for a dynamic environment. I am wondering if I am missing a trick to get my consumer updated? I am running the Ember+ Viewer and can see update messages received as I change data in TinyEmber+ - this is what I need in my application :-)

For this purpose you will need to subscribe to the PropertyChanged event of all parameters.

**Comment by AstecSteveB** [comment]
I've parsed the tree down to the Parameter level and attached a handler to the PropertyChanged event. After changing the same parameter value in TinyEmber+, the PropertyChanged event does not fire. Re-reading the documentation it says that the consumer will automatically send GetDirectory commands to get updates for all declared parameters. If you could update your dynamic console application example to show this working that would be great.

**Comment by andreashuber-lawo** [comment]
> If you could update your dynamic console application example to show this working that would be great.

I'll do that, stay tuned.

**Comment by AstecSteveB** [comment]
On a slightly different subject - I used the sample code to try and walk a Junger frame at a customer site and it threw and exception with: "The remote host has failed to answer a KeepAliveRequest within half the timeout period". The Enmber+ Viewer can connect and I am able to view the tree. However, in the message window it reports a Glow Error: Glow DTD version mismatch: found version 2.10, expected 2.31!

**Comment by andreashuber-lawo** [comment]
> If you could update your dynamic console application example to show this working that would be great.

http://lawo.github.io/ember-plus-sharp/html/7cdb703a-14dd-42d3-8ea2-28a9b8af6663.htm

**Comment by andreashuber-lawo** [comment]
> On a slightly different subject - I used the sample code to try and walk a Junger frame at a customer site and it threw and exception with: "The remote host has failed to answer a KeepAliveRequest within half the timeout period".

The standard keep-alive timeout is 3 seconds. Some providers struggle to answer KA requests when they are busy, please see whether increasing the timeout changes anything.

http://lawo.github.io/ember-plus-sharp/html/7345C981.htm

> The Enmber+ Viewer can connect and I am able to view the tree. However, in the message window it reports a Glow Error: Glow DTD version mismatch: found version 2.10, expected 2.31!

I'm not the author of the Ember+ Viewer, but I believe you can safely ignore that message.

**Comment by andreashuber-lawo** [comment]
I assume this has been resolved. If not, feel free to reopen.

**Comment by AstecSteveB** [comment]
Yes, thank you. With our driver architecture I will investigate the S101 interface as I need a more polling style approach

**Comment by andreashuber-lawo** [comment]
> Yes, thank you. With our driver architecture I will investigate the S101 interface as I need a more polling style approach

You *can* do polling with Ember+ Sharp, I just don't understand why you'd want that? Can you please explain?

**Comment by AstecSteveB** [comment]
The drivers run as hidden console applications. They handle multiple physical devices with each Device being polled at a custom frequency. When the polling is due, a worker thread is launched that runs to completion. I'd therefore want to create the connection to the Ember device on start-up (or after an error), and then read the contents of the configured tree items during the poll task.

**Comment by andreashuber-lawo** [comment]
> When the polling is due, a worker thread is launched that runs to completion. I'd therefore want to create the connection to the Ember device on start-up (or after an error), and then read the contents of the configured tree items during the poll task.

You can certainly do that, namely by awaiting Consumer.CreateAsync and then immediately calling Consumer.Dispose. You can still call the Consumer.Root getter afterwards and process the retrieved data.

However, as you might have noticed already, Consumer.CreateAsync is often rather resource-hungry, especially for large trees. This is because the data describing the part of the tree you are interested in needs to be queried, received and parsed. But, after this initial setup phase, only changes are sent back and forth, which tends to be orders of magnitude cheaper. So, if at all possible, I would advise you to keep your Consumer objects connected, which gives you immediate access to all the current data when the polling is due.

**Comment by AstecSteveB** [comment]
Thanks. I did run tests based on your description above but I only got updated parameter data if I disposed of the consumer and then re-created it (I can't await the on-change method described in the documentation as it blocks until the data changes). If I still use the consumer approach I will look to implement a static interface to greatly reduce the number of tree elements.

**Comment by andreashuber-lawo** [comment]
> I did run tests based on your description above but I only got updated parameter data if I disposed of the consumer and then re-created it

No, if you keep your consumer alive then the values of all parameters should always be identical to the values of their respective provider parameters. Changes are automatically and continually propagated back and forth until you call Consumer.Dispose(). If that doesn't work for you then this sounds like a bug.

> (I can't await the on-change method described in the documentation as it blocks until the data changes).

If I understand your scenario correctly, then you don't have to wait for the PropertyChanged event to fire. In your polling handler, you'd simply take the already existing Consumer object and grab whatever data you need from the tree and process it (remember that all properties of all elements are continually kept in sync).

**Comment by AstecSteveB** [comment]
OK, I'll re-run my test and if it doesn't work I'll post the code here. Thanks again!

**Comment by andreashuber-lawo** [comment]
Quick question: To implement the polling interval, are you by any chance calling Thread.Sleep?

**Comment by AstecSteveB** [comment]
Yes, it was used in my previous test where I created a loop to monitor the tree values.

**Comment by andreashuber-lawo** [comment]
> Yes, it was used in my previous test where I created a loop to monitor the tree values.

Ahh, this is almost certainly the problem then. Thread.Sleep blocks the current thread, which is something you should almost never do in code that uses async and await. Please try Task.Delay instead.

**Comment by AstecSteveB** [comment]
Good spot! Using Task.Delay allows the tree updates to come through (it shows my lack of knowledge of the async environment). I'll need to think about a different driver implementation as the code has to be wrapped by an AsyncPump.Run() and this doesn't exit unless the client/consumer is disposed. I could implement a poll-style with static elements to reduce the tree size but connecting/disconnecting seems every inefficient and will put a needless load on the remote device. The other approach is to have the AsyncPump.Run() active for the lifetime of the driver. Now that I am getting updates this seems the best approach.
Thanks for your patience!

**Comment by andreashuber-lawo** [comment]
> I'll need to think about a different driver implementation as the code has to be wrapped by an AsyncPump.Run() and this doesn't exit unless the client/consumer is disposed.

Right, you must call both `Consumer.Dispose()` and `S101Client.Dispose()`, otherwise `AsyncPump.Run()` will never complete.

> The other approach is to have the AsyncPump.Run() active for the lifetime of the driver. Now that I am getting updates this seems the best approach.

Correct.

**Comment by AstecSteveB** [comment]
Using the updated test application to try against a real Junger frame, I am getting an error of form: 'The provider failed to send the children for the element with the path..."
The S101Client timeout is set to 30000 and the buffer size is set to 32000. 
I've also set the TcpClient receive timeout to 30000.
Are there any other timeouts that can be configured, assuming this is a timeout issue?

**Comment by andreashuber-lawo** [comment]
> The S101Client timeout is set to 30000 and the buffer size is set to 32000.

The default for the buffer size of 8192 should be adequate for pretty much all applications.

> I've also set the TcpClient receive timeout to 30000.

That's probably not necessary either...

> Are there any other timeouts that can be configured, assuming this is a timeout issue?

Yes, most likely you need to increase the default of 10000 passed to `Consumer.CreateAsync`:

<http://lawo.github.io/ember-plus-sharp/html/8F30E950.htm>

**Comment by AstecSteveB** [comment]
I've set all timeouts to 60000 and now I don't get an error but the Consumer.CreateAsync hasn't returned (after apprimately 5 minutes of waiting). The Ember+ Viewer can connect and view all items. Note that the Junger Frame has 20 modules present.

**Comment by andreashuber-lawo** [comment]
> I've set all timeouts to 60000 and now I don't get an error but the Consumer.CreateAsync hasn't returned (after apprimately 5 minutes of waiting).

Hmm, that's odd. Can you please share the snippet of code that you use to connect? Thanks.

**Comment by AstecSteveB** [comment]
I have the variable outside a using as I was testing having a separate  connection process:

        private sealed class MyRoot : DynamicRoot<MyRoot> {}
        private static S101Client client;
        private static Consumer<MyRoot> consumer;
        
        static void Main(string[] args)
        {
            if (args.Count() == 1)
            {
                try
                {
                    AsyncPump.Run(
                        async () =>
                        {
                            // Create TCP connection
                            var tcpClient = new TcpClient();
                            await tcpClient.ConnectAsync(args[0], 9000);
                            tcpClient.ReceiveTimeout = 60000;

                            // Establish S101 protocol
                            // S101 provides message packaging, CRC integrity checks and a keep-alive mechanism.
                            var stream = tcpClient.GetStream();
                            client = new S101Client(tcpClient, stream.ReadAsync, stream.WriteAsync, null, 60000, 32000);
                            consumer = await Consumer<MyRoot>.CreateAsync(client, 60000);
                            while (true)
                            {
                                WriteChildren(consumer.Root, 0);
                                await Task.Delay(1000);
                                if (Console.KeyAvailable)
                                {
                                    consumer.Dispose();
                                    client.Dispose();
                                }
                            }
                        });
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }
            else
            {
                Console.WriteLine("No address specified");
            }
            Console.WriteLine("Hit any key to close...");
            Console.ReadKey(true);
        }

**Comment by andreashuber-lawo** [comment]
At first glance, the code looks fine. I can't test it right now, as I don't currently have access to a provider with sufficiently many elements in its tree. I'll get back to you on that later. In the mean time, can you please try without the line `tcpClient.ReceiveTimeout = 60000;`? It seems unlikely that this will change anything, but just to make sure...

I suspect part of the problem lies in the amount of data transferred. Can you please also try with the static interface, requesting only the data you really need.

**Comment by AstecSteveB** [comment]
Using Ember+ Viewer, the tree structure identifiers are:
IP Address
__C8000
____c8087[00h]
______status
________preset
__________value

Can you confirm that the definitions are correct please as I am getting the following error:
No data value available for the required property EmberTest.Program+C8000.C8087
in the node with the path /C8000/c8087[00h].

        private sealed class C8000Root : Root<C8000Root>
        {
            internal C8000 C8000 { get; private set; }
        }

        private sealed class C8000 : FieldNode<C8000>
        {
            [Element(Identifier = "c8087[00h]")]
            internal C8000 C8087 { get; private set; }
        }

        private sealed class C8087 : FieldNode<C8087>
        {
            internal Status Status { get; private set; }
        }

        private sealed class Status : FieldNode<Status>
        {
            internal IntegerParameter Preset { get; private set; }
        }

**Comment by andreashuber-lawo** [comment]
I guess this line

`internal C8000 C8087 { get; private set; }`

should rather be

`internal C8087 C8087 { get; private set; }`

?

**Comment by AstecSteveB** [comment]
I still got and error but it is further down the tree:
No data value available for the required property EmberTest.Program+_C8000.C8087.Status_
in the node with the path /C8000/c8087[00h].

**Comment by andreashuber-lawo** [comment]
> I still got and error but it is further down the tree:

Ahh yes, I missed the other errors first time round: Both the Status and Preset property must be decorated with an appropriate Element attribute (the identifier is case-sensitive).

**Comment by AstecSteveB** [comment]
One step further:

No data value available for the required property EmberTest.Program+Status.Preset in the node with the path /C8000/c8087[00h]/status.

It takes 30 seconds before the error is reported.

        private sealed class C8000Root : Root<C8000Root>
        {
            internal C8000 C8000 { get; private set; }
        }

        private sealed class C8000 : FieldNode<C8000>
        {
            [Element(Identifier = "c8087[00h]")]
            internal C8087 C8087 { get; private set; }
        }

        private sealed class C8087 : FieldNode<C8087>
        {
            [Element(Identifier = "status")]
            internal Status Status { get; private set; }
        }

        private sealed class Status : FieldNode<Status>
        {
            [Element(Identifier = "preset")]
            internal IntegerParameter Preset { get; private set; }
        }

**Comment by andreashuber-lawo** [comment]
Can you please post a screen shot of the tree in the Ember+ Viewer? Thanks.

**Comment by AstecSteveB** [comment]
![emberview](https://cloud.githubusercontent.com/assets/17786024/13992919/e68db24a-f115-11e5-8b54-e7e259e54579.png)

**Comment by andreashuber-lawo** [comment]
I have a suspicion, it appears that the provider sends the identifier out of order: C-0 appears in the fifth position instead of the first. Due to an oversight in the Ember+ specification this is technically allowed, but all providers I have so far seen send the identifier in the first position. Unfortunately, the Ember+ Sharp Library currently requires that the identifier is sent first. I can probably fix this, but not without sacrificing a fair bit of processing performance.

To confirm my suspicion, can you please connect as you did before, but this time with a logger...

`using Lawo.EmberPlusSharp.Glow;`
...
`var logger = new S101Logger(GlowTypes.Instance, File.CreateText("log.xml"));`
`client = new S101Client(tcpClient, stream.ReadAsync, stream.WriteAsync, logger, 60000, 32000);`

... and attach the log file to your next post?

Thanks!

**Comment by AstecSteveB** [comment]
Please find attached log file as requested:

[log.zip](https://github.com/Lawo/ember-plus-sharp/files/193078/log.zip)

**Comment by andreashuber-lawo** [comment]
Thank you very much, this confirms my suspicion. I will fix this as soon as I can.

**Comment by AstecSteveB** [comment]
No problem. Thank you for your support.

**Comment by andreashuber-lawo** [comment]
The bug should be fixed. As expected, the performance hit is rather hefty (+~70%). I will try to optimize this further. May I ask you to try again with the current release?

Thanks for your patience!

**Comment by AstecSteveB** [comment]
Using the static tree data is being returned :+1: 
When I tried to use the dynamic tree I got the error: 'The remote host has failed to answer a KeepAliveRequest within half the timeout period'
Is it possible to create a static tree programmatically as I could convert my driver configuration to a tree before the CreateAsync?

**Comment by andreashuber-lawo** [comment]
> When I tried to use the dynamic tree I got the error: 'The remote host has failed to answer a KeepAliveRequest within half the timeout period'

Depending on how long you can afford to wait for `Consumer.CreateAsync` to return, you might be able to fix this by increasing the timeout passed to `S101Client`. Your mileage may vary though, internally we have providers where the retrieval of the full tree takes more than 5 minutes and the resulting in-memory data structure uses more than 100MB. Consequently, nobody ever downloads the full tree for these providers.

> Is it possible to create a static tree programmatically as I could convert my driver configuration to a tree before the CreateAsync?

Not currently, but it shouldn't be too hard to implement.

**Comment by andreashuber-lawo** [comment]
Let me clarify: There's no way to use the static interface programmatically. After all, the compiler must know the types so that you can access their properties in your program. However, the dynamic interface can be extended, so that only the relevant nodes are requested from the provider.

**Comment by AstecSteveB** [comment]
> Let me clarify: There's no way to use the static interface programmatically. After all, the compiler must know the types so that you can access their properties in your program. However, the dynamic interface can be extended, so that only the relevant nodes are requested from the provider.

This was my understanding. It would be the most efficient approach for my driver interface too. Is this something you could implement in the near future?

**Comment by andreashuber-lawo** [comment]
> Is this something you could implement in the near future?

Define "near future" ;-). Seriously, I'm currently swamped with other work, but I'll probably have something usable in two weeks. Can you test and implement with the static interface in the mean time?

**Comment by AstecSteveB** [comment]
If you could have something to test in two weeks that would be fantastic - I am not wishing to add to your stress levels and thank you for your continued support. I can perform some more basic testing but with the configurable nature of our system there can be many permutations of driver setup so the static approach isn't really a viable solution.

**Comment by andreashuber-lawo** [comment]
BTW, have you had a look at the mixed interface part of the tutorial yet? Depending on how configurable your system is, the mixed interface approach could help you to confine the full retrieval of data to the branches you're interested in.

**Comment by AstecSteveB** [comment]
I have taken another look at the mixed mode. I would need to perform a detailed site survey to review how all the frames are populated (currently not all the equipment has Ember enabled). This would only be a temporary solution as it would be fixed for one manufacturer.

**Comment by andreashuber-lawo** [comment]
Ok, understood. I'll let you know as soon as I have something usable.

**Comment by andreashuber-lawo** [comment]
As always, things took longer than anticipated. Now that I'm on it, it turns out that #21 will require quite a bit of effort to get right. With all the other stuff that's currently on my plate, I'm afraid it will be **at least** another two weeks before I might have something for you to try. Sorry!

**Comment by AstecSteveB** [comment]
Ok. Thanks for your continued support.

**Comment by andreashuber-lawo** [comment]
I've pushed a commit that shows how the interface for #21 will probably look like. If you like, you can have a look at:

- [ChildrenRequestPolicy.cs](https://github.com/Lawo/ember-plus-sharp/blob/master/Lawo.EmberPlusSharp/Model/ChildrenRequestPolicy.cs)
- [INode.cs](https://github.com/Lawo/ember-plus-sharp/blob/master/Lawo.EmberPlusSharp/Model/INode.cs), lines 20-28
- [Consumer.cs](https://github.com/Lawo/ember-plus-sharp/blob/master/Lawo.EmberPlusSharp/Model/Consumer.cs), lines 188-198

**Comment by andreashuber-lawo** [comment]
It looks like I'm done. Please have a look at the new release and let me know whether the new feature works as you would expect. Here are direct links to the documentation:

- [ChildrenRetrievalPolicy](http://lawo.github.io/ember-plus-sharp/html/B60F4F2.htm)
- [INode.ChildrenRetrievalPolicy](http://lawo.github.io/ember-plus-sharp/html/9C1A2E53.htm)
- [Consumer<TRoot>.CreateAsync](http://lawo.github.io/ember-plus-sharp/html/1A95E950.htm), also see other overloads.

**Comment by AstecSteveB** [comment]
Sorry, I've been busy on other projects. I'll try and test this later today.

Thanks

**Comment by AstecSteveB** [comment]
Sorry for the delay. I've rebuilt by solution and confirmed that by testing with TinyEmber the original approach works. I'm trying to understand how I define the items I am interested in. For example, using the Sapphire example, if I just wanted to access "Sapphire/Sources/FPGM 1/Fader/dB Value" and "Sapphire/Sources/FPGM 2/Fader/dB Value" how would this be achieved?

**Comment by andreashuber-lawo** [comment]
In the [Main Method](http://lawo.github.io/ember-plus-sharp/html/f6285c3c-ef54-453e-90ad-5546ec1a7a1d.htm) you'd call [CreateAsync](http://lawo.github.io/ember-plus-sharp/html/8F30E950.htm) and pass [ChildrenRetrievalPolicy.DirectOnly](http://lawo.github.io/ember-plus-sharp/html/B60F4F2.htm). When CreateAsync returns, the [Children](http://lawo.github.io/ember-plus-sharp/html/162F3ADE.htm) property of [Consumer.Root](http://lawo.github.io/ember-plus-sharp/html/F35B9A31.htm) will contain the node with the identifier "Sapphire", but the "Sapphire" node itself does not yet have any children. You'd then set the [ChildrenRetrievalPolicy](http://lawo.github.io/ember-plus-sharp/html/9C1A2E53.htm) property of the "Sapphire" node to [ChildrenRetrievalPolicy.DirectOnly](http://lawo.github.io/ember-plus-sharp/html/B60F4F2.htm) and await [Consumer.SendAsync](http://lawo.github.io/ember-plus-sharp/html/B5499501.htm). When SendAsync returns the Children property of the "Sapphire" should contain its direct children (the nodes "identity" and "Sources"). You'd then repeat the process with the "Sources" node and so forth until you have all children you are interested in.

**Comment by AstecSteveB** [comment]
Perfect. I'll implement and report back

**Comment by AstecSteveB** [comment]
This is working fine with TinyEmber :+1: . I'll now test it with a Junger frame

**Comment by AstecSteveB** [comment]
Pulling Meter data back from a Junger frame:

![ember](https://cloud.githubusercontent.com/assets/17786024/15043889/c516804a-12c8-11e6-8ad7-4389bb119f01.png)

**Comment by andreashuber-lawo** [comment]
Congratulations! 👍

**Comment by AstecSteveB** [comment]
Thank you so much for your support

**Comment by andreashuber-lawo** [comment]
You're welcome, I'm glad I could help.
