### ISSUE TITLE
EnumParameter with wrong number in enum

### ISSUE THREAD

**Issue by roobfried** [Lawo/ember-plus-sharp#26]
Hi,
when I try to receive Parameter, I get this Error-Message:
"The number of named constants of the enum specified for the parameter with the path [...] does not match the number of entries sent by the provider."
Adding a dummy-entry at the end, does solve that problem.
GlowAnalyzer does not give a hint.
Using v1.2.1604.4003 against a Jünger T*AP Audioprocessor

**Comment by andreashuber-lawo** [comment]
> when I try to receive Parameter, I get this Error-Message:
 "The number of named constants of the enum specified for the parameter with the path [...] does not match the number of entries sent by the provider."
> Adding a dummy-entry at the end, does solve that problem.

Yes, that is intentional. The number of entries as well as their integer values must match. Does this create a problem for you?

> GlowAnalyzer does not give a hint.

The error you are seeing has nothing to do with the Ember+ protocol itself. It is purely an error of the consumer which alerts you to the fact that the enum type you specified cannot be used to represent some values that are allowed by the provider. Since GlowAnalyzerProxy cannot know what enum type you specified, it cannot possibly give you a hint here.

**Comment by roobfried** [comment]
Yes, I missed an added empty element at the end of the enumeration.
Do I get it right, this is implied by the last newline in GlowAnalyzer-Log?

<enumeration type="UTF8String">GR1/CH1
GR1/CH2
GR1/CH3
GR1/CH4
GR2/CH1
GR2/CH2
GR2/CH3
GR2/CH4
GR3/CH1
GR3/CH2
GR3/CH3
GR3/CH4
GR4/CH1
GR4/CH2
GR4/CH3
GR4/CH4
</enumeration>
<minimum type="Integer">0</minimum>
<maximum type="Integer">15</maximum>

I guess this is provider-implementation: but why would you want to add an empty element?

Von: Andreas Huber [mailto:notifications@github.com]
Gesendet: Freitag, 3. Juni 2016 11:52
An: Lawo/ember-plus-sharp <ember-plus-sharp@noreply.github.com>
Cc: Sommer, Robert [n-tv] <Robert.Sommer@n-tv.de>; Author <author@noreply.github.com>
Betreff: Re: [Lawo/ember-plus-sharp] EnumParameter with wrong number in enum (#26)


when I try to receive Parameter, I get this Error-Message:
"The number of named constants of the enum specified for the parameter with the path [...] does not match the number of entries sent by the provider."
Adding a dummy-entry at the end, does solve that problem.

Yes, that is intentional. The number of entries as well as their integer values must match. Does this create a problem for you?

GlowAnalyzer does not give a hint.

The error you are seeing has nothing to do with the Ember+ protocol itself. It is purely an error of the consumer which alerts you to the fact that the enum type you specified cannot be used to represent some values that are allowed by the provider. Since GlowAnalyzerProxy cannot know what enum type you specified, it cannot possibly give you a hint here.

**Comment by andreashuber-lawo** [comment]
> Yes, I missed an added empty element at the end of the enumeration.
> Do I get it right, this is implied by the last newline in GlowAnalyzer-Log?

It seems so. According to the Ember+ specification, the different values need to be **separated** by \n characters in the string. There's no mention that the last entry needs to be terminated by a \n. Given the min and max values, it appears that this is a bug in the provider.
