### ISSUE TITLE
How to use the ChildrenRetrievalPolicy.DirectOnly ?

### ISSUE THREAD

**Issue by radio42** [Lawo/ember-plus-sharp#33]
As far as I understood the `ChildrenRetrievalPolicy` concept, you might first only use the DirectOnly mode and then request for each INode child again the DirectOnly to retrieve further children etc. inbetween you call _consumer.SendAsync() to get the additional nodes...
This doesn't seem to work... I am using the dynamic mode...

Here is my code:

```
_consumer = await Consumer<MyRoot>.CreateAsync(_client, 9000, ChildrenRetrievalPolicy.DirectOnly);
_root = _consumer.Root;
// _root at this point contains 1 x 'Sapphire' node - which is correct!
// 'Sapphire' node itself does not contain any children yet.

foreach (var child in _root.Children)
{
    if (child is INode)
        ((INode)child).ChildrenRetrievalPolicy = ChildrenRetrievalPolicy.DirectOnly;
}
await _consumer.SendAsync();
// at this point _root now contains 2 x a 'Sapphire' node ?!
// both having 2 child nodes each...
// if the code is continued and repeated for the child nore; all nodes are duplicated and exist twice!!
```

Why is this?
Is this a bug? Or am I using the policy incorrectly?

**Comment by andreashuber-lawo** [comment]
This is definitely a bug, thanks for reporting.

**Comment by radio42** [comment]
Any idea when approximately this might be fixed?

**Comment by andreashuber-lawo** [comment]
Not yet, I'll be able to spend a little time tomorrow. I'll keep you posted...

**Comment by andreashuber-lawo** [comment]
Initial tests show this should be fixed now in the source code. If you're eager to use this feature immediately, you might want to compile the dlls yourself. Or, you can wait for the release, which will probably happen later today.

**Comment by radio42** [comment]
I can confirm, that it is now working fine.
Thanks!
