### ISSUE TITLE
Enum parameter value is of type Int64?!

### ISSUE THREAD

**Issue by radio42** [Lawo/ember-plus-sharp#34]
Is this indentend?
Wouldn't an Int32 value be better suited?

E.g., assume you have an IParameter element of type Enum and what to 'print' both its numeric value as well as the Enum key name. You would have to first cast the parameter.Value to a long and then to an int to access the paramater.EnumMap dictionary...
`parameter.EnumMap[(int)(long)parameter.Value].Key`

To me this looks unnecessarily complicated - or is there a greater reason behind?

**Comment by andreashuber-lawo** [comment]
This is all according to the Ember+ Spec. Integer parameters have 64bit values, but the EnumMap is restricted to 32bit values. I agree that this is nonsense (EnumMap should be 64bit too), but I stick to the spec whenever possible. I would suggest you use EnumParameter if possible in your scenario.
