### ISSUE TITLE
SynchronizationContext - Console app/Windows service

### ISSUE THREAD

**Issue by fredrikbergholtz-sr** [Lawo/ember-plus-sharp#36]
I would like to use this library from within a Windows Service and those don't have a SynchronizationContext. 

Do you have any recommendations for how I can proceed? I started to read about making a custom SynchronizationContext in [this](https://www.codeproject.com/Articles/31971/Understanding-SynchronizationContext-Part-I) article series but I feel a little bit out of my depth there.

**Comment by andreashuber-lawo** [comment]
I would recommend to have the service start a thread and use AsyncPump in its entry method, as shown at the bottom of [this page](http://lawo.github.io/ember-plus-sharp/html/f6285c3c-ef54-453e-90ad-5546ec1a7a1d.htm).

**Comment by andreashuber-lawo** [comment]
I assume my suggestion worked. If not, feel free to reopen this issue.
