### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by AstecSteveB** [Lawo/ember-plus-sharp#44]
Hi,

I am observing relatively high CPU usage - it appears to be approximately 2% per connection. Is this something that has been observed elsewhere?

I am using v1.2.1604.29003 of the DLL.

Regards,
Steve

**Comment by andreashuber-lawo** [comment]
In general, the CPU usage should be proportional to the amount of traffic. CPU usage that occurs after Consumer.Create returns is usually attributable to frequent parameter updates. Especially streamed parameters are typically updated very frequently (multiple times each second).

If you want to know what causes the traffic, I'd suggest to use Glow Analyzer Proxy to write a log file.

**Comment by AstecSteveB** [comment]
Is there anything client side that can be set to limit the frequency of updates?

**Comment by andreashuber-lawo** [comment]
No, the update frequency is determined by the provider. However, you might be able to reduce the traffic simply by not retrieving parameters you are not interested in.
