### ISSUE TITLE
Lawo.EmberPlusSharp.Model.EmberOption is gone

### ISSUE THREAD

**Issue by radio42** [Lawo/ember-plus-sharp#49]
Hi,

in the latest changes, it seems, that the Lawo.EmberPlusSharp.Model.EmberOption has been removed.
So far I used the Lawo.EmberPlusSharp.Model.EmberOption.IgnoreMatrices option.
Is this gone= Am I missing something? or what is the alternative?

Many Greets,
Bernd

**Comment by andreashuber-lawo** [comment]
I don't remember ever having provided such an option. IIRC, you implemented this yourself, no?

**Comment by radio42** [comment]
Need to check ;-)

**Comment by radio42** [comment]
My fault! I am getting old... it was my extension ;-)
