### ISSUE TITLE
Add support for Ember+ Matrix types

### ISSUE THREAD

**Issue by andreashuber-lawo** [Lawo/ember-plus-sharp#7]

**Comment by radio42** [comment]
Hi Andreas,

first I'd like to express my congrats on this lib! Excellent work.

I hope it will officially be supported also in the future, as I plan to use it within my radio automation software (ProppFrexx ONAIR).

A few questions though:

1) Any news on this one? Looks like Matrix Types are still not recognized/supported?
(at least I couldn't detect any IMatrix when traversing all INode childs...)

2) I couldn't find any details about automatic Keep-Alive-Requests (from a consumer to a provider)? Does the 'S101Client' handle/send these automatically?  If yes, can I somehow adjust the interval rate?
Or do I have to send Keep-Alive-Requests manually? If yes, how?

3) What about the following extensions?
- Schema
- Templates

Many Thanks in advance!

Regards,
Bernd

**Comment by andreashuber-lawo** [comment]
Hi Bernd

Thanks for your feedback, it is very much appreciated!

> 1. Any news on this one? Looks like Matrix Types are still not recognized/supported?
(at least I couldn't detect any IMatrix when traversing all INode childs...)

Unfortunately, matrices are not yet supported, due to lack of demand. Now that we have demand, I will bring this up again internally. I can't promise anything but we might find some time to finally implement this.

> 2. I couldn't find any details about automatic Keep-Alive-Requests (from a consumer to a provider)? 

It's documented in the [S101Client Remarks](http://lawo.github.io/ember-plus-sharp/html/9F3D3A83.htm). However, I agree that it's not very visible, I'll add links to S101Client members #31.

> 3. What about the following extensions?
> - Schema
> - Templates

- Schemas are already fully supported through the [SchemaIdentifiers Property](http://lawo.github.io/ember-plus-sharp/html/D1E448CC.htm).
- Templates are currently unsupported, mainly because it is a strictly optional feature of Ember+. Providers must always offer the option to serve content in the "traditional" way.

**Comment by radio42** [comment]
Hi Andreas,

many thanks for all!

And yes, your API is much more intuitive to use than the standard ember-plus one  - especially when coding a consumer ;-)
Keep on that great work!

Greets,
Bernd
